defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: rajawali/rajawali:release-1.0
  environment:
    TERM: dumb

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Execute Gradle
          command: |
            echo "org.gradle.parallel=false" >> gradle.properties
            echo "org.gradle.daemon=false" >> gradle.properties
            echo "org.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -Dfile.encoding=UTF-8" >> gradle.properties

            ./gradlew build --no-daemon

